name: Deploy Lambda to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies and zip Summarizer Lambda function
      run: |
        mkdir -p summarizer_package
        pip install -t summarizer_package/ requests 
        cp lambdas/summarizer_lambda.py summarizer_package/lambda_function.py
        cd summarizer_package
        zip -r ../summarizer_lambda.zip .
        cd ..

    - name: zip Uploader Lambda function
      run: |
        mkdir -p uploader_package
        cp lambdas/uploader_lambda.py uploader_package/lambda_function.py
        cd uploader_package
        zip -r ../uploader_lambda.zip .
        cd ..
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Uploader Lambda Deploy
      uses: appleboy/lambda-action@v0.2.0
      with:
        function_name: uploader_lambda
        zip_file: uploader_lambda.zip
    
    - name: Summerizer Lambda Deploy
      uses: appleboy/lambda-action@v0.2.0
      with:
        function_name: summarizer_lambda
        zip_file: summarizer_lambda.zip

    - name: Get function URL and set webhook
      if: github.ref == 'refs/heads/main'
      run: |
        URL=$(aws lambda get-function-url-config --function-name uploader_lambda --query 'FunctionUrl' --output text)

        WEBHOOK_RESPONSE=$(curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/setWebhook?url=${URL}&drop_pending_updates=true")

        echo "curl -X POST https://api.telegram.org/bot<YOUR_TOKEN>/setWebhook?url=$FUNCTION_URL"
        echo "Verifying webhook info..."
        curl --request GET \
          --url "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/getWebhookInfo"
